In [1]:
import pandas as pd
from os import listdir
from os.path import isfile, join

import sqlite3

In [3]:
dfAllSongs = pd.read_csv('playlist_df.csv')
dfAllSongs.head()

Song        Artist            Chords
0             island-in-the-sun        weezer       Am,Em,D,C,G
1      all-along-the-watchtower  jimi-hendrix          Bb,Cm,Ab
2                 back-in-black          acdc  A,D,C,B,E,G,A/C#
3                   rebel-rebel   david-bowie          E,A,Bm,D
4  should-i-stay-or-should-i-go     the-clash           A,G,D,F

In [4]:
thisSong = pd.read_csv('ug_chords10/radiohead - creep.csv')
thisSong

Song     Artist    Chords   Label
0  creep  radiohead  G,Cm,C,B  novice

In [ ]:
chordPath  = '/Users/aaronlevi/Documents/Insight2020/chordRec/ug_chords10/'
chordFiles = [f for f in listdir(chordPath) if isfile(join(chordPath, f))]


for iSong in range(0, len(chordFiles)):
    dfThisSong = pd.read_csv(chordPath+chordFiles[iSong])
    dfAllSongs = pd.concat([dfAllSongs, dfThisSong], axis=0)

# dfAllSongs = dfAllSongs.reset_index(drop=True)
# dfAllSongs


In [10]:
dfAllSongs = dfAllSongs.reset_index(drop=True)
dfAllSongs


Artist  \
0                               weezer   
1                         jimi-hendrix   
2                                 acdc   
3                          david-bowie   
4                            the-clash   
5                            aerosmith   
6                                queen   
7                            the-doors   
8                               zz-top   
9                            bob-dylan   
10                               cream   
11        creedence-clearwater-revival   
12                        janis-joplin   
13                         steppenwolf   
14                        dire-straits   
15                  jefferson-airplane   
16                                kiss   
17                                rush   
18                              prince   
19                          the-police   
20                         cheap-trick   
21                        led-zeppelin   
22                                acdc   
23                        stevie-nicks   
24                           joan-jett   
25        creedence-clearwater-revival   
26               derek-and-the-dominos   
27                          don-mclean   
28                           bob-dylan   
29                       black-sabbath   
...                                ...   
1301                      mumford-sons   
1302                   misc-soundtrack   
1303                     amy-macdonald   
1304                    sara-bareilles   
1305                       wilbur-soot   
1306  lukas-nelson-promise-of-the-real   
1307               misc-computer-games   
1308                         lil-nas-x   
1309                     john-coltrane   
1310                      procol-harum   
1311                       the-beatles   
1312                          bon-jovi   
1313                             queen   
1314                       bruno-major   
1315                       the-strokes   
1316                                lp   
1317                     ariana-grande   
1318                          bon-iver   
1319          crosby-stills-nash-young   
1320                     stevie-wonder   
1321                          bastille   
1322               5-seconds-of-summer   
1323                     misc-cartoons   
1324                   aretha-franklin   
1325                 the-moldy-peaches   
1326                        pink-floyd   
1327                       frank-ocean   
1328                     joni-mitchell   
1329                     barry-manilow   
1330                     frank-sinatra   

                                                 Chords         Label  \
0                                           Am,Em,D,C,G           NaN   
1                                              Bb,Cm,Ab           NaN   
2                                      A,D,C,B,E,G,A/C#           NaN   
3                                              E,A,Bm,D           NaN   
4                                               A,G,D,F           NaN   
5                                               A,C,G,D           NaN   
6                                     Am,Em,A,C,B,G,F#m           NaN   
7                    Am7,D#,A#,A,D,Bm7,B,E,G#,C,F,G,F#m           NaN   
8                                            A,D,C,F,Eb           NaN   
9                                       Em,C,Dm7,F,Dm,G           NaN   
10                                            A,C,D,F,G           NaN   
11                                              D,G,C,F           NaN   
12                              A7,A,C,D,C/G,D7,E7,G7,G           NaN   
13                                           A,D,E,C#,G           NaN   
14                  A7,Bb,A,C,Fmaj,Cmaj,F,Bbmaj,Dm,Dmin           NaN   
15                                            E,A,F#m,B           NaN   
16                                            A,D,E,F,G           NaN   
17                                       A,C,D,B,E,F#,G           NaN   
18                                      

In [18]:
dfAllSongs.drop('Unnamed: 0', axis=1, inplace=True)

In [19]:
# dfAllSongs.to_sql('chords_list', con=engine, if_exists='append')
dfAllSongs

Artist  \
0                               weezer   
1                         jimi-hendrix   
2                                 acdc   
3                          david-bowie   
4                            the-clash   
5                            aerosmith   
6                                queen   
7                            the-doors   
8                               zz-top   
9                            bob-dylan   
10                               cream   
11        creedence-clearwater-revival   
12                        janis-joplin   
13                         steppenwolf   
14                        dire-straits   
15                  jefferson-airplane   
16                                kiss   
17                                rush   
18                              prince   
19                          the-police   
20                         cheap-trick   
21                        led-zeppelin   
22                                acdc   
23                        stevie-nicks   
24                           joan-jett   
25        creedence-clearwater-revival   
26               derek-and-the-dominos   
27                          don-mclean   
28                           bob-dylan   
29                       black-sabbath   
...                                ...   
1301                      mumford-sons   
1302                   misc-soundtrack   
1303                     amy-macdonald   
1304                    sara-bareilles   
1305                       wilbur-soot   
1306  lukas-nelson-promise-of-the-real   
1307               misc-computer-games   
1308                         lil-nas-x   
1309                     john-coltrane   
1310                      procol-harum   
1311                       the-beatles   
1312                          bon-jovi   
1313                             queen   
1314                       bruno-major   
1315                       the-strokes   
1316                                lp   
1317                     ariana-grande   
1318                          bon-iver   
1319          crosby-stills-nash-young   
1320                     stevie-wonder   
1321                          bastille   
1322               5-seconds-of-summer   
1323                     misc-cartoons   
1324                   aretha-franklin   
1325                 the-moldy-peaches   
1326                        pink-floyd   
1327                       frank-ocean   
1328                     joni-mitchell   
1329                     barry-manilow   
1330                     frank-sinatra   

                                                 Chords         Label  \
0                                           Am,Em,D,C,G           NaN   
1                                              Bb,Cm,Ab           NaN   
2                                      A,D,C,B,E,G,A/C#           NaN   
3                                              E,A,Bm,D           NaN   
4                                               A,G,D,F           NaN   
5                                               A,C,G,D           NaN   
6                                     Am,Em,A,C,B,G,F#m           NaN   
7                    Am7,D#,A#,A,D,Bm7,B,E,G#,C,F,G,F#m           NaN   
8                                            A,D,C,F,Eb           NaN   
9                                       Em,C,Dm7,F,Dm,G           NaN   
10                                            A,C,D,F,G           NaN   
11                                              D,G,C,F           NaN   
12                              A7,A,C,D,C/G,D7,E7,G7,G           NaN   
13                                           A,D,E,C#,G           NaN   
14                  A7,Bb,A,C,Fmaj,Cmaj,F,Bbmaj,Dm,Dmin           NaN   
15                                            E,A,F#m,B           NaN   
16                                            A,D,E,F,G           NaN   
17                                       A,C,D,B,E,F#,G           NaN   
18                                      

In [20]:
dfAllSongs.to_csv('allSongsBasic.csv', index=False)


In [3]:
conn = sqlite3.connect('/Users/aaronlevi/Documents/sql_db/chords_list.db')
cur = conn.cursor()

# dfAllSongs.to_sql('basic_info', con=conn, if_exists='append')


In [45]:
cur.execute("select * from basic_info limit 5;")

results = cur.fetchall()
print(results)

[(0, 'weezer', 'Am,Em,D,C,G', None, 'island-in-the-sun'), (1, 'jimi-hendrix', 'Bb,Cm,Ab', None, 'all-along-the-watchtower'), (2, 'acdc', 'A,D,C,B,E,G,A/C#', None, 'back-in-black'), (3, 'david-bowie', 'E,A,Bm,D', None, 'rebel-rebel'), (4, 'the-clash', 'A,G,D,F', None, 'should-i-stay-or-should-i-go')]


In [46]:
df = pd.read_sql_query("SELECT * FROM basic_info", conn)
df

index                            Artist  \
0         0                            weezer   
1         1                      jimi-hendrix   
2         2                              acdc   
3         3                       david-bowie   
4         4                         the-clash   
5         5                         aerosmith   
6         6                             queen   
7         7                         the-doors   
8         8                            zz-top   
9         9                         bob-dylan   
10       10                             cream   
11       11      creedence-clearwater-revival   
12       12                      janis-joplin   
13       13                       steppenwolf   
14       14                      dire-straits   
15       15                jefferson-airplane   
16       16                              kiss   
17       17                              rush   
18       18                            prince   
19       19                        the-police   
20       20                       cheap-trick   
21       21                      led-zeppelin   
22       22                              acdc   
23       23                      stevie-nicks   
24       24                         joan-jett   
25       25      creedence-clearwater-revival   
26       26             derek-and-the-dominos   
27       27                        don-mclean   
28       28                         bob-dylan   
29       29                     black-sabbath   
...     ...                               ...   
1301   1301                      mumford-sons   
1302   1302                   misc-soundtrack   
1303   1303                     amy-macdonald   
1304   1304                    sara-bareilles   
1305   1305                       wilbur-soot   
1306   1306  lukas-nelson-promise-of-the-real   
1307   1307               misc-computer-games   
1308   1308                         lil-nas-x   
1309   1309                     john-coltrane   
1310   1310                      procol-harum   
1311   1311                       the-beatles   
1312   1312                          bon-jovi   
1313   1313                             queen   
1314   1314                       bruno-major   
1315   1315                       the-strokes   
1316   1316                                lp   
1317   1317                     ariana-grande   
1318   1318                          bon-iver   
1319   1319          crosby-stills-nash-young   
1320   1320                     stevie-wonder   
1321   1321                          bastille   
1322   1322               5-seconds-of-summer   
1323   1323                     misc-cartoons   
1324   1324                   aretha-franklin   
1325   1325                 the-moldy-peaches   
1326   1326                        pink-floyd   
1327   1327                       frank-ocean   
1328   1328                     joni-mitchell   
1329   1329                     barry-manilow   
1330   1330                     frank-sinatra   

                                                 Chords         Label  \
0                                           Am,Em,D,C,G          None   
1                                              Bb,Cm,Ab          None   
2                                      A,D,C,B,E,G,A/C#          None   
3                                              E,A,Bm,D          None   
4                                               A,G,D,F          None   
5                                               A,C,G,D          None   
6                                     Am,Em,A,C,B,G,F#m          None   
7                    Am7,D#,A#,A,D,Bm7,B,E,G#,C,F,G,F#m          None   
8                                            A,D,C,F,Eb          None   
9                                       Em,C,Dm7,F,Dm,G          None   
10                                            A,C,D,F,G          None   
11                                              D,G,C,F          None   
12                

In [47]:
# SELECT name, commission FROM salesman;

dfb_test = pd.read_sql_query("SELECT Artist, Song FROM basic_info", conn)
dfb_test


Artist  \
0                               weezer   
1                         jimi-hendrix   
2                                 acdc   
3                          david-bowie   
4                            the-clash   
5                            aerosmith   
6                                queen   
7                            the-doors   
8                               zz-top   
9                            bob-dylan   
10                               cream   
11        creedence-clearwater-revival   
12                        janis-joplin   
13                         steppenwolf   
14                        dire-straits   
15                  jefferson-airplane   
16                                kiss   
17                                rush   
18                              prince   
19                          the-police   
20                         cheap-trick   
21                        led-zeppelin   
22                                acdc   
23                        stevie-nicks   
24                           joan-jett   
25        creedence-clearwater-revival   
26               derek-and-the-dominos   
27                          don-mclean   
28                           bob-dylan   
29                       black-sabbath   
...                                ...   
1301                      mumford-sons   
1302                   misc-soundtrack   
1303                     amy-macdonald   
1304                    sara-bareilles   
1305                       wilbur-soot   
1306  lukas-nelson-promise-of-the-real   
1307               misc-computer-games   
1308                         lil-nas-x   
1309                     john-coltrane   
1310                      procol-harum   
1311                       the-beatles   
1312                          bon-jovi   
1313                             queen   
1314                       bruno-major   
1315                       the-strokes   
1316                                lp   
1317                     ariana-grande   
1318                          bon-iver   
1319          crosby-stills-nash-young   
1320                     stevie-wonder   
1321                          bastille   
1322               5-seconds-of-summer   
1323                     misc-cartoons   
1324                   aretha-franklin   
1325                 the-moldy-peaches   
1326                        pink-floyd   
1327                       frank-ocean   
1328                     joni-mitchell   
1329                     barry-manilow   
1330                     frank-sinatra   

                                                   Song  
0                                     island-in-the-sun  
1                              all-along-the-watchtower  
2                                         back-in-black  
3                                           rebel-rebel  
4                          should-i-stay-or-should-i-go  
5                                         sweet-emotion  
6                            another-one-bites-the-dust  
7                                         light-my-fire  
8                                             la-grange  
9                                  like-a-rolling-stone  
10                                sunshine-of-your-love  
11                                        fortunate-son  
12                                   me-and-bobby-mcgee  
13                                      born-to-be-wild  
14                                     sultans-of-swing  
15                                     somebody-to-love  
16                               rock-and-roll-all-nite  
17                                           tom-sawyer  
18                                       when-doves-cry  
19                                every-breath-you-take  
20                                i-want-you-to-want-me  
21                                              kashmir  
22                                      highway-to-hell  
23                                 

In [48]:
# cur.close()
# conn.close()


In [4]:
X = pd.read_sql_query("SELECT * FROM features", conn)
X = X.iloc[57:]
X.drop('index', axis=1, inplace=True)
X = X.reset_index(drop=True)

print(X.head())

y = pd.read_sql_query("SELECT label FROM basic_info", conn)
y = y.iloc[57:]
y = y.reset_index(drop=True)
# y = pd.factorize(y['Label'])[0]

print(y.head())
# print(y[:5])



     tempo  duration_m  time_signature  energy  n_unique_chords  \
0  172.286    3.533967             4.0   0.292                3   
1   96.996    1.981967             4.0   0.771               12   
2   75.646    5.499333             4.0   0.223                5   
3  120.042    3.588000             4.0   0.762                6   
4  150.190    5.052000             4.0   0.558                8   

   n_difficult_chords  chord_per_min  
0                   0       0.848904  
1                  12       6.054592  
2                   1       0.909201  
3                   4       1.672241  
4                   4       1.583531  
          Label
0        novice
1      advanced
2      advanced
3  intermediate
4  intermediate


In [5]:
X['label']=y
X.head()
print(len(X))

X.dropna(axis=0, how='any', inplace=True)
print(len(X))

y = pd.factorize(X['label'])[0]
print(y[:5])
X.drop(['duration_m', 'label'], axis = 1, inplace=True)

X.head()

2373
2361
[0 1 1 2 2]


tempo  time_signature  energy  n_unique_chords  n_difficult_chords  \
0  172.286             4.0   0.292                3                   0   
1   96.996             4.0   0.771               12                  12   
2   75.646             4.0   0.223                5                   1   
3  120.042             4.0   0.762                6                   4   
4  150.190             4.0   0.558                8                   4   

   chord_per_min  
0       0.848904  
1       6.054592  
2       0.909201  
3       1.672241  
4       1.583531

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

mul_lr = LogisticRegression( 
            multi_class='multinomial', 
            solver='newton-cg', 
            fit_intercept=True 
                            ).fit(X_train, y_train) 


In [7]:
predictions = mul_lr.predict(X_test)


In [8]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))


[[110   5  47]
 [ 20 104  42]
 [ 49  35  61]]
              precision    recall  f1-score   support

           0       0.61      0.68      0.65       162
           1       0.72      0.63      0.67       166
           2       0.41      0.42      0.41       145

    accuracy                           0.58       473
   macro avg       0.58      0.58      0.58       473
weighted avg       0.59      0.58      0.58       473



In [9]:
pd.DataFrame(mul_lr.coef_, columns=X_train.columns)

tempo  time_signature    energy  n_unique_chords  n_difficult_chords  \
0 -0.001363        0.017027 -0.304807        -0.115725           -0.086223   
1  0.002445       -0.152916  0.392115         0.057977            0.139425   
2 -0.001082        0.135889 -0.087308         0.057748           -0.053202   

   chord_per_min  
0      -0.021924  
1       0.067507  
2      -0.045583

In [97]:
print(y[:5])

lab = pd.read_sql_query("SELECT label FROM basic_info", conn)
lab = lab.iloc[57:]
lab = lab.reset_index(drop=True)
print(lab[:5])

[0 1 1 2 2]
          Label
0        novice
1      advanced
2      advanced
3  intermediate
4  intermediate


In [107]:
import numpy as np
intLabel = np.ones(len(lab))
intLabel = intLabel*6

print(intLabel)

[6. 6. 6. ... 6. 6. 6.]


In [110]:
for ix in range(0, len(lab)):
    if lab['Label'][ix] == 'novice':
        intLabel[ix] = 0
    elif lab['Label'][ix] == 'intermediate':
        intLabel[ix] = 1
    else:
        intLabel[ix] = 2

In [11]:
# y = intLabel

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)
X_train, X_test, y_train, y_test = train_test_split(X_scale, y, test_size=0.2, random_state=101)

mul_lr = LogisticRegression( 
            multi_class='multinomial', 
            solver='newton-cg', 
            fit_intercept=True 
                            ).fit(X_train, y_train) 

predictions = mul_lr.predict(X_test)

print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

[[110   5  47]
 [ 20 104  42]
 [ 49  35  61]]
              precision    recall  f1-score   support

           0       0.61      0.68      0.65       162
           1       0.72      0.63      0.67       166
           2       0.41      0.42      0.41       145

    accuracy                           0.58       473
   macro avg       0.58      0.58      0.58       473
weighted avg       0.59      0.58      0.58       473



In [137]:
mul_lr.coef_

array([[-1.36393856, -0.60159309],
       [ 0.63323049, -0.64099755],
       [ 0.73070806,  1.24259063]])

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaler.fit(X)
X_scale = scaler.transform(X)

In [134]:
X.drop(['tempo', 'time_signature', 'energy'], axis=1, inplace=True)
X.head()

n_unique_chords  n_difficult_chords
0                3                   0
1               12                  12
2                5                   1
3                6                   4
4                8                   4